# Project information
site_name: Python-Generic-Project
# defeine TOC or order of website-
nav:
  - Home: index.md
  - APIReference.md

site_author: Samarth G
site_description: >-
  DESCRIPTION

# Repository
repo_name: Samm-G/Python-Generic-Project-Template
repo_url: https://github.com/Samm-G/Python-Generic-Projects-Template

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: red
      accent: orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: red
      accent: orange
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Samm-G
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Samm-G
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/Samm-G
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/Samm-G/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/Samm-G"  target="_blank" rel="noopener">Samarth G</a>